name: flutter_telnyx_voice_ai_widget
description: "Flutter Voice AI Embeddable Widget"
version: 1.0.0
homepage: https://telnyx.com/
repository: https://github.com/team-telnyx/flutter-telnyx-voice-ai-widget
issue_tracker: https://github.com/team-telnyx/flutter-telnyx-voice-ai-widget/issues

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  telnyx_webrtc: ^3.0.0
  uuid: ^4.5.1
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  flutter_webrtc: ^0.14.2

flutter:
  assets:
    - assets/images/
